/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "Today is wendy",
  "description": "red velet 思密达",
  "base": "/vuepress-demo/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/vuepress-demo/assets/img/favicon.ico"
      }
    ],
    [
      "meta",
      {
        "name": "keywords",
        "content": "vuepress介绍,vuepress说明,shawn"
      }
    ],
    [
      "meta",
      {
        "name": "author",
        "content": "shawn"
      }
    ]
  ],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/assets/img/logo.png",
        "heroText": "Today is wendy",
        "tagline": "韩国女歌手，女子演唱组合Red Velvet成员",
        "actionText": "看完了,快速学习 →",
        "actionLink": "/about/",
        "features": [
          {
            "title": "简洁至上",
            "details": "以 Markdown 为中心的项目结构，以最少的配置帮助你专注于写作。"
          },
          {
            "title": "Vue驱动",
            "details": "享受 Vue + webpack 的开发体验，在 Markdown 中使用 Vue 组件，同时可以使用 Vue 来开发自定义主题。"
          },
          {
            "title": "高性能",
            "details": "VuePress 为每个页面预渲染生成静态的 HTML，同时在页面被加载的时候，将作为 SPA 运行。"
          }
        ],
        "footer": "MIT Licensed | Copyright © 2018-present Evan You"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-44b74d2e",
      "path": "/"
    },
    {
      "frontmatter": {},
      "regularPath": "/about/",
      "relativePath": "about/README.md",
      "key": "v-3165ac9a",
      "path": "/about/"
    },
    {
      "title": "nginx教程",
      "frontmatter": {
        "sidebarDepth": 4
      },
      "regularPath": "/nginx/",
      "relativePath": "nginx/README.md",
      "key": "v-607369c0",
      "path": "/nginx/",
      "headers": [
        {
          "level": 2,
          "title": "第一章 基础及安装",
          "slug": "第一章-基础及安装"
        },
        {
          "level": 3,
          "title": "一、nginx 功能介绍",
          "slug": "一、nginx-功能介绍"
        },
        {
          "level": 3,
          "title": "二、nginx可以提供的服务",
          "slug": "二、nginx可以提供的服务"
        },
        {
          "level": 3,
          "title": "三、nginx 的优点",
          "slug": "三、nginx-的优点"
        },
        {
          "level": 3,
          "title": "四、nginx应用场合",
          "slug": "四、nginx应用场合"
        },
        {
          "level": 3,
          "title": "五、nginx实战",
          "slug": "五、nginx实战"
        }
      ]
    }
  ],
  "themeConfig": {
    "lastUpdated": "上次更新时间",
    "logo": "/assets/img/logo.png",
    "nav": [
      {
        "text": "首页",
        "link": "/"
      },
      {
        "text": "About",
        "link": "/about/"
      },
      {
        "text": "Nginx",
        "link": "/nginx/"
      },
      {
        "text": "Languages",
        "ariaLabel": "Language Menu",
        "items": [
          {
            "text": "Chinese",
            "link": "/language/chinese/"
          },
          {
            "text": "Japanese",
            "link": "/language/japanese/"
          }
        ]
      }
    ],
    "sidebar": "auto"
  }
}